### ISSUE TITLE
Scrolling speed of the first word

### ISSUE THREAD

**Issue by maximodeveloper** [xuexiangjys/MarqueeTextView#1]
Hello. This is the best Marquee TextView I found here on github, very nice job! I'm using this on my project if you don't mind.
I have only one problem and I was wondering if you could help me.
I noticed that the first word is always faster at the first time it appears. Then, after it goes away, the other words are normal.
Do you know what's going on here? Do you have any idea how to fix it?

**Comment by xuexiangjys** [comment]
thank you for your issues。i have fix this bug on version 1.3.1。
